name: Build

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Enable debug logging
        run: echo "##[debug]Debugging is enabled"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Uncomment the following lines to fail the job when the Quality Gate is red
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
