
deploy:
    needs: build-analyze-scan
    runs-on: self-hosted # Use your self-hosted runner label here
    steps:
      - name: Pull the Docker image
        run: docker pull sevenajay/tic-tac-toe:latest

      - name: Trivy image scan
        run: trivy image sevenajay/tic-tac-toe:latest # Add Trivy scan command here

      - name: Run the container
        run: docker run -d --name ticgame -p 3000:3000 sevenajay/tic-tac-toe:latest
      
      - name: Update kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD

      - name: Deploy to EKS
        run: kubectl apply -f deployment-service.yml
